### ISSUE TITLE
FFTW library is required or not?

### ISSUE THREAD

**Issue by penfe** [MelodyShih/cufinufft#4]
Dear Yu-hsuan Shih,

Probably your cufinufft can works without fftw3 as the Makefile below?

~~~make
# FFTWNAME=fftw3
# FFTW=$(FFTWNAME)$(PRECSUFFIX)
#
# LIBS=-lm -lcudart -lstdc++ -lnvToolsExt -lcufft -lcuda -l$(FFTW)
LIBS=-lm -lcudart -lstdc++ -lnvToolsExt -lcufft -lcuda
~~~

**Comment by MelodyShih** [comment]
Dear penfe, 

Thank you for your interest in the library. Yes, you are right. FFTW library is not required here. 
This repository is actually a little bit outdated. It has been moved here: https://github.com/flatironinstitute/cufinufft, which contains the latest development.

Best,
Yu-hsuan

**Comment by penfe** [comment]
Thanks Yu-hsuan for your comment.
